spring.application.name=roommatch-api

server.port=8081
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=roommatch_db;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=162115!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

spring.security.user.name=admin
spring.security.user.password=admin
jwt.secret=roommatch_super_secret_key_2026_para_firmar_tokens_seguro_123456
jwt.expiration=86400000
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha